include: package:friflex_lint_rules/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.yaml"
    - "app_services/aurora/**"
    - "/app_services/aurora/**"
    - "**/app_services/aurora/**"