name: friflex_starter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  meta: 1.15.0
  equatable: 2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  friflex_lint_rules:
    hosted: https://pub.friflex.com
    version: 4.0.1

flutter:
  uses-material-design: true
  generate: false
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/lottie/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
      
flutter_gen:
    options: 
      output: lib/gen/
      line_length: 100
    integrations:
      flutter_svg: true
      lottie: true
        
