name: friflex_starter
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  envied: 1.1.1
  go_router: 15.1.2
  flutter_bloc: 9.1.1
  provider: 6.1.5
  dio: 5.8.0+1
  intl: 0.20.2
  flutter_svg: 2.1.0
  flutter_localizations:
    sdk: flutter
  lottie: 3.3.1

  # Пакеты для отладки
  talker_flutter: 4.8.0
  talker_dio_logger: 4.8.0
  talker_bloc_logger: 4.8.0
  talker_logger: 4.8.0

  equatable: 2.0.7

  theme_tailor_annotation: 3.0.2

  ### основной сервис с интерфейсами
  i_app_services:
    path: ./app_services/i_app_services

  ### реализация сервисов ###
  ### В зависимости от платформы ###
  app_services:
    path: app_services/base/app_services ### Базовая реализация ###
    #path: app_services/aurora/app_services ### Аврора реализация ###

dev_dependencies:
  flutter_test:
    sdk: flutter
  envied_generator: 1.1.1
  build_runner: 2.4.15
  flutter_gen_runner: 5.10.0
  flutter_gen: 5.10.0
  flutter_lints: 6.0.0
  theme_tailor: 3.0.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/lottie/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400

flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true
