name: app_services
description: "Аврора ОС сервисы для приложения"
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.16.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Зависимости для сервиса защищенного хранилища
  flutter_secure_storage: 8.0.0
  flutter_secure_storage_aurora:
    git:
      url: https://gitlab.com/omprussia/flutter/flutter-community-plugins/flutter_secure_storage_aurora.git
      ref: aurora-0.5.3

  # Зависимости для работы с путями (плагин встроен в sdk flutter 3.27.3)
  path_provider: 2.1.5

  # Зависимости для работы с открытием ссылок (плагин встроен в sdk flutter 3.27.3)
  url_launcher: 6.3.1

  # Обязательные интерфейсы
  i_app_services:
    path: ../../i_app_services

dev_dependencies:
  flutter_lints: 6.0.0
