name: i_app_services
description: "Хранит в себе все интерфейсы для реализации общих сервисов"
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  friflex_lint_rules:
    hosted: https://pub.friflex.com
    version: 4.0.1
