name: app_services
description: "Базовые сервисы для приложения"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # Зависимости для сервиса защищенного хранилища
  flutter_secure_storage: 9.2.4

  # Зависимости для сервиса незащищенного хранилища
  shared_preferences: 2.3.5

  # для работы с путями в хранилища
  path_provider: 2.1.5

  # Обязательные интерфейсы
  i_app_services:
    path: ../../i_app_services

dev_dependencies:
  friflex_lint_rules:
    hosted: https://pub.friflex.com
    version: 4.0.1
