name: app_services
description: "Базовые сервисы для приложения"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # Зависимости для сервиса защищенного хранилища
  flutter_secure_storage: 9.2.4

  # Зависимости для сервиса незащищенного хранилища
  shared_preferences: 2.3.5

  # для работы с путями в хранилища
  path_provider: 2.1.5

  # Зависимости для сервиса внешних ссылок
  url_launcher: 6.3.1

  # Обязательные интерфейсы
  i_app_services:
    path: ../../i_app_services

dev_dependencies:
  flutter_lints: 6.0.0
