name: app_services
description: "Huawei сервисы для приложения"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Обязательные интерфейсы
  i_app_services:
    path: ../../i_app_services

dev_dependencies:
  flutter_lints: 6.0.0
